### ISSUE TITLE
Cannot run any container

### ISSUE THREAD

**Issue by geloizi** [nabla-containers/runnc#22]
I've tried run `nabla-node-base` and it fails:

```
docker run --rm --runtime=runnc nablact/nabla-node-base                                                                                              

docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/32559322d11dacf0a7b80d2662c36bf3e45197f15630dab41d0830c647df3d33/log.json: no such file or directory): /usr/local/bin/runnc did not terminate sucessfully: unknown.
```

Docker version - 18.03.1-ce, host os - Ubuntu 18.04

**Comment by ricarkol** [comment]
Hey @lumjjb, trying to figure out where is that error coming from. `log.json` is definitely not created by `runnc`, so it has to be `runc`. Then, the issue seems that `runc` but can't tell why `..3d33/` is not there.

@geloizi thanks for the report. Favor please, do you have a `/tmp/runnc.log` log file in the system where you tried this. If so, could you paste the tail please?

**Comment by lumjjb** [comment]
Let me take a look at this. That error that you see there is because we are not currently writing our error into the log that docker is expecting to query for its error message. Like @ricarkol said, the error messages show right now in `/tmp/runnc.log`.

**Comment by lumjjb** [comment]
Log propagation implemented in https://github.com/nabla-containers/runnc/pull/23. (Awaiting merge).

**Comment by geloizi** [comment]
I found the problem myself. It didn't start due to the lack of `genisoimage`.

**Comment by ricarkol** [comment]
Awesome, thanks @geloizi 

Adding genisoimage to the list of required "stuff". @lumjjb let's add genisoimage as a library (libiso) again?

**Comment by lumjjb** [comment]
Looks like the problem is resolved!

**Comment by Yansslc** [comment]
@geloizi Hey~ I just have the same problem, can you detail the way to solve this? Many thanks!

**Comment by lumjjb** [comment]
Hi @Yansslc ! Can you link the output that you're seeing and also the commit of `runnc` you are running, as well as your Operating system version and kernel version?

Thanks!
