### ISSUE TITLE
cannot run the docker image hello-world

### ISSUE THREAD

**Issue by abdennour** [nabla-containers/runnc#25]
Just after setting up the runtime NABLA, I tried : 

```sh
docker run --runtime=nabla-runtime  hello-world
```

And this is the error

```
docker: Error response from daemon: OCI runtime create failed: Entrypoint is not a .nabla file: unknown.
ERRO[0000] error waiting for container: context canceled 
```

Did you require any restrictions with the Entrypoint layer (`Entrypoint is not a .nabla file:`) ?

**Comment by lumjjb** [comment]
Hi @abdennour, right now, one of our limitations (https://github.com/nabla-containers/runnc#limitations) is that we can only run nabla built containers. We currently do not support running unmodified regular processes. However, we do have some pre-packaged docker images that you can build on top of (`python`, `node`, `redis`). 

You may find the resources in this repo helpful! https://github.com/nabla-containers/nabla-demo-apps

**Comment by lumjjb** [comment]
Let's follow up this discussion in this thread:

https://github.com/nabla-containers/runnc/issues/27
