### ISSUE TITLE
Support for kubernetes via containerd runtime

### ISSUE THREAD

**Issue by lumjjb** [nabla-containers/runnc#28]
Running on kubernetes has been something that we've thought about doing, but is still an item on the TODO. 

There has been some developments in the community since we first started looking at integrating with kubernetes. We've been able to run nabla container processes on k8s containers in the past, so running as a runtime should be an ideal next step. 

@kelseyhightower has suggested that we should be able to run on the OCI-like interface on kubernetes. 

@abdennour mentioned several options to integrate `runnc` into containerd with the containerd runtime in containerd v1.10. 
- https://kubernetes.io/blog/2017/11/containerd-container-runtime-options-kubernetes/ 
- https://github.com/kata-containers/documentation/blob/master/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md

**Comment by lumjjb** [comment]
[RuntimeClass](https://github.com/kubernetes/features/issues/585) seems to be a good complimentary feature to work with. As mentioned from friendly folks at https://github.com/kata-containers.

**Comment by raravena80** [comment]
This also applies to CRIO https://github.com/kubernetes-incubator/cri-o

**Comment by lumjjb** [comment]
Hey Ricardo! :) Wanted to tag you, but couldn't get your github handle. I was talking to other Ricardo (@ricarkol) and @djwillia about how we may explore contributing our stuff to one of the CRIs, and one of the considerations was networking. Considering that we would ideally want to work with tap devices, should frakti be a good option to integrate with?

**Comment by raravena80** [comment]
@lumjjb I don't think it's needed imo. The reason Frakti works with Kata is because Kata is a combination of two projects runV and Clear Containers. runV ran with Frakti, so Kata also supports it. I believe running with the contained CRI shim or CRIO would be enough.

**Comment by abdennour** [comment]
Thank you @lumjjb .

If someone wants to read the related article, you could find it [here](http://elegance.abdennoor.com/running-containers-nabla-runtime#prospects).

**Comment by lumjjb** [comment]
Addressed in: https://github.com/nabla-containers/runnc/pull/35 !
