### ISSUE TITLE
nabla-cont should be run as init in runnc

### ISSUE THREAD

**Issue by lumjjb** [nabla-containers/runnc#50]
There shouldn't be a reason that `runnc-cont` is a separate binary (besides legacy reasons :) ).

We should aim to move the `runnc-cont` startup logic to https://github.com/nabla-containers/runnc/blob/master/libcontainer/init_nabla.go.

**Comment by zhuangqh** [comment]
working on this

**Comment by lumjjb** [comment]
Awesome! :) Do ping us if you have any questions!

**Comment by zhuangqh** [comment]
The code of this project is a little bit c-style....

**Comment by lumjjb** [comment]
lol.... Sorry about that, the code from `runnc-cont` was originally just almost directly translated from another language - which was a long time ago before we started `runnc`.

Feel free to just move it as is... and rewriting it go-style more with pointer receivers than passing in 1000 arguments can come later.

But if you're feeling like it, please do :)

**Comment by zhuangqh** [comment]
@lumjjb sorry for inactive for a long time since I was busy with my own work...😂 I will rebase my code and submit a pull request this weekend. Don't wait for me.😅

**Comment by lumjjb** [comment]
No worries! - All good. we have a couple of other things to look at at the moment, so all good! :)

**Comment by lumjjb** [comment]
@zhuangqh come join our slack channel! slack.nabla-containers.com

**Comment by lumjjb** [comment]
This issue has been resolved by #56 ! Thanks @zhuangqh . Closing this issue!
